### ISSUE TITLE
Users Page: Space out the new user form so it isnt just one skinny column (consistent styling)

### ISSUE THREAD

**Issue by booherbg** [Fraser-Ltd/fraser-work-orders#60]

**Comment by booherbg** [comment]
Or add whitespace so boxes aren't smashed together

**Comment by kvisness** [comment]
This has been completed so far as the spacing is good.  Leaving open until we complete the final Material UI for the mobile and tablet views.

**Comment by kvisness** [comment]
This has been adjusted.
