### ISSUE TITLE
Resident Coordinator Homepage: Add some instructions around what the conditions are to see work orders (assigned? belongs to their property? etc.) 

### ISSUE THREAD

**Issue by booherbg** [Fraser-Ltd/fraser-work-orders#66]

**Comment by kvisness** [comment]
I think we should look at the wording under Current Work Orders for the Resident Coordinator landing page.

**Comment by kvisness** [comment]
Also, should the RC have the ability to change the Status of a Work Order?  Currently, if RC changes a work order's status to Submitted, it goes back to the Admin user as a Work Order to Assign.
